run:
  # Таймаут на выполнение линтера (иногда на CI нужно больше времени)
  timeout: 5m
  # Включаем проверку тестов
  tests: true

linters-settings:
  govet:
    # Проверка на затенение переменных (очень частая ошибка у новичков: err := ...)
    check-shadowing: true
  gocyclo:
    # Цикломатическая сложность. Если функция сложнее 15 — рефактори, дроби на части.
    min-complexity: 15
  maligned:
    # Подскажет, как оптимизировать структуры по памяти (padding)
    suggest-new: true
  dupl:
    # Порог обнаружения дублирования кода
    threshold: 100
  goconst:
    # Ругается, если строка повторяется более 3 раз. Выноси в константы!
    min-len: 3
    min-occurrences: 3
  nolintlint:
    # Запрещает писать просто //nolint, требует указывать причину и конкретный линтер
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    # Базовые
    - errcheck      # Обязательная проверка ошибок
    - gosimple      # Упрощение кода
    - govet         # Стандартный верификатор
    - ineffassign   # Бесполезные присваивания
    - staticcheck   # Статический анализ
    - typecheck     # Проверка типов
    - unused        # Неиспользуемый код

    # Стиль и качество
    - revive        # Замена устаревшему golint, следит за стилем
    - bodyclose     # ВАЖНО: следит, чтобы ты делал defer resp.Body.Close()
    - noctx         # Следит, чтобы в http запросы передавался контекст
    - gocyclo       # Сложность функций
    - gosec         # Проверка на уязвимости (hardcoded credentials и т.д.)
    - prealloc      # Подсказывает, где можно аллоцировать слайс заранее (perf)
    - unconvert     # Лишние конвертации типов

issues:
  # Исключаем некоторые папки (например, автогенерацию)
  exclude-dirs:
    - docs
    - bin
  # Не ограничиваем кол-во однотипных ошибок (показывай всё)
  max-same-issues: 0